### ISSUE TITLE
No response on Android. 

### ISSUE THREAD

**Issue by TohWei** [tkowalczyk/SimpleCustomGestureFrame#2]
I was running your sample app under this env:
Xamarin forms: 1.3.1
Xamarin.Adnroid 4.20.0.37

I had it work for the iOS, but not Android. 
No error during the compilation, no issue and no bug.  But, no response when I swipe it on Android. 
I done the testing via Xamarin Android Player, as well as on a actual physical device (Samsung galaxy S4), but both having the same result. 

Am I missing something? Anything else that I need to include?

**Comment by tkowalczyk** [comment]
Hhmm you are right, it probably happened after upgrade to Xamarin.Forms 1.3 but at this moment I don't know why this is not working on Android. I will try to find out in spare time, please let me know if you will cope with this with your own.
