### ISSUE TITLE
Gesture Frame with CarouselView

### ISSUE THREAD

**Issue by acaliaro** [tkowalczyk/SimpleCustomGestureFrame#4]
Hi @tkowalczyk and thanks for your work.
I have tried to insert your GestureFrame inside a CarouselView but it does not work very well. It's very difficult to have a SwipeTop.. can you take a look? Thanks.

**Comment by tkowalczyk** [comment]
Hi @acaliaro this repository is not being updated for some time and this might be the reason for your issue. Furthermore Xamarin.Forms now is using different approach for dealing with gestures so this is the second thing.

**Comment by sivamuralidhar3** [comment]
Hi @tkowalczyk 
I am using you GestureFrame in my project all the events are working fine,Thanks for your sample. but i cant find touch event in it.can you help me with this..!!!
Thanks.

**Comment by acaliaro** [comment]
For touch Xamarin forms use TapGestureRecognizer

**Comment by sivamuralidhar3** [comment]
Hi @acaliaro  
when i am using tap gesture event which is in xamarin.forms default it is working in ios but not working in android.
