### ISSUE TITLE
xaml gestureFrame

### ISSUE THREAD

**Issue by micuentadecasa** [tkowalczyk/SimpleCustomGestureFrame#6]
Hi, I'm trying to add your gestureFrame but in Xaml and it says this:

/Users/luis/Dropbox/projects/rasoApp/xxx/obj/Debug/testFramePage.xaml.g.cs(17,17): Error CS0246: The type or namespace name `GestureFrame' could not be found. Are you missing`SimpleCustomGesureFrame' using directive? (CS0246) (xxx)

it works using the gestureFrame declaratively but not in xaml

**Comment by tkowalczyk** [comment]
have you added a namespace needed in your xaml file?

**Comment by micuentadecasa** [comment]
no, please tell me how

**Comment by tkowalczyk** [comment]
Please, better read some docs. For example here:
https://developer.xamarin.com/guides/xamarin-forms/custom-renderer/introduction/

You will have to add smth similiar to this code:

`<ContentPage
    ...
    xmlns:local="clr-namespace:CustomRenderer;assembly=CustomRenderer"
    ...>
    ...
    <local:MyEntry Text="In Shared Code" />
    ...
</ContentPage>`

If you solved it with your own it will be better for you and you also will learn something,

**Comment by micuentadecasa** [comment]
You were right, it was a 5 minute task and I learned something new. Thanks @tkowalczyk
