### ISSUE TITLE
UWP

### ISSUE THREAD

**Issue by jessicarich1980** [tkowalczyk/SimpleCustomGestureFrame#8]
Hi Guys,

Any idea if there is support for UWP?

**Comment by tkowalczyk** [comment]
Hi probably no, because this project is no longer maintained.

**Comment by jessicarich1980** [comment]
Hi Tomasz,

Do you know if it's possible to add events such as StartSwipeLeft
StartSwipeRight with the offset as parameter so that I can use TranslateTo
with x offset to mimic action of slowly swiping?

**Comment by tkowalczyk** [comment]
Probably yes, but definietly it is a task to investigate with your own.
