### ISSUE TITLE
Blank screen in andoid

### ISSUE THREAD

**Issue by rubenc57** [tkowalczyk/SimpleCustomGestureFrame#9]
Hello

It was working for android and ios, now it shows a blank screen in android

Greetings
rubenc

**Comment by rubenc57** [comment]
???

**Comment by tkowalczyk** [comment]
This project is not maintained for over 2 years, so please understand that I don't know what can make this problem. Please use debugger, read documentation and try to deal with it.

**Comment by rubenc57** [comment]
Thank you
